eureka:
  instance:
    prefer-ip-address: false
  client:    service-url:      defaultZone: http://localhost:8761/eureka/
      
security:    oauth2:      resource:
        user-info-uri: http://auth-service/uaa/users/current
        token-info-uri: http://localhost:8080/uaa/oauth/check_token
        
logging:  level:    org.springframework.security: DEBUG